/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as DealsRouteImport } from './routes/deals'
import { Route as AiRouteImport } from './routes/ai'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DepartmentsIndexRouteImport } from './routes/departments.index'
import { Route as DepartmentsIdRouteImport } from './routes/departments.$id'
import { Route as DealsDealCodeRouteImport } from './routes/deals.$dealCode'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const DealsRoute = DealsRouteImport.update({
  id: '/deals',
  path: '/deals',
  getParentRoute: () => rootRouteImport,
} as any)
const AiRoute = AiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DepartmentsIndexRoute = DepartmentsIndexRouteImport.update({
  id: '/departments/',
  path: '/departments/',
  getParentRoute: () => rootRouteImport,
} as any)
const DepartmentsIdRoute = DepartmentsIdRouteImport.update({
  id: '/departments/$id',
  path: '/departments/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DealsDealCodeRoute = DealsDealCodeRouteImport.update({
  id: '/$dealCode',
  path: '/$dealCode',
  getParentRoute: () => DealsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/deals': typeof DealsRouteWithChildren
  '/docs': typeof DocsRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/deals/$dealCode': typeof DealsDealCodeRoute
  '/departments/$id': typeof DepartmentsIdRoute
  '/departments/': typeof DepartmentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/deals': typeof DealsRouteWithChildren
  '/docs': typeof DocsRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/deals/$dealCode': typeof DealsDealCodeRoute
  '/departments/$id': typeof DepartmentsIdRoute
  '/departments': typeof DepartmentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/deals': typeof DealsRouteWithChildren
  '/docs': typeof DocsRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/deals/$dealCode': typeof DealsDealCodeRoute
  '/departments/$id': typeof DepartmentsIdRoute
  '/departments/': typeof DepartmentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai'
    | '/deals'
    | '/docs'
    | '/reports'
    | '/settings'
    | '/deals/$dealCode'
    | '/departments/$id'
    | '/departments/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai'
    | '/deals'
    | '/docs'
    | '/reports'
    | '/settings'
    | '/deals/$dealCode'
    | '/departments/$id'
    | '/departments'
  id:
    | '__root__'
    | '/'
    | '/ai'
    | '/deals'
    | '/docs'
    | '/reports'
    | '/settings'
    | '/deals/$dealCode'
    | '/departments/$id'
    | '/departments/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiRoute: typeof AiRoute
  DealsRoute: typeof DealsRouteWithChildren
  DocsRoute: typeof DocsRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  DepartmentsIdRoute: typeof DepartmentsIdRoute
  DepartmentsIndexRoute: typeof DepartmentsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deals': {
      id: '/deals'
      path: '/deals'
      fullPath: '/deals'
      preLoaderRoute: typeof DealsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai': {
      id: '/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/departments/': {
      id: '/departments/'
      path: '/departments'
      fullPath: '/departments/'
      preLoaderRoute: typeof DepartmentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/departments/$id': {
      id: '/departments/$id'
      path: '/departments/$id'
      fullPath: '/departments/$id'
      preLoaderRoute: typeof DepartmentsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deals/$dealCode': {
      id: '/deals/$dealCode'
      path: '/$dealCode'
      fullPath: '/deals/$dealCode'
      preLoaderRoute: typeof DealsDealCodeRouteImport
      parentRoute: typeof DealsRoute
    }
  }
}

interface DealsRouteChildren {
  DealsDealCodeRoute: typeof DealsDealCodeRoute
}

const DealsRouteChildren: DealsRouteChildren = {
  DealsDealCodeRoute: DealsDealCodeRoute,
}

const DealsRouteWithChildren = DealsRoute._addFileChildren(DealsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiRoute: AiRoute,
  DealsRoute: DealsRouteWithChildren,
  DocsRoute: DocsRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  DepartmentsIdRoute: DepartmentsIdRoute,
  DepartmentsIndexRoute: DepartmentsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
